### ISSUE TITLE
Build fail for iOS

### ISSUE THREAD

**Issue by dltmd6262** [adjust/cocos2dx_sdk#10]
Hi! I just integrated the sdk for android, but I get a huge error when I try to build for iOS as so:

<img width="246" alt="screen shot 2016-05-16 at 5 23 08 pm" src="https://cloud.githubusercontent.com/assets/14027017/15284218/074b3abc-1b8b-11e6-9807-00b2e66dbb04.png">

It would be great if you could give me some help on this!

xcode version: 7.3.1

**Comment by uerceg** [comment]
Hi @dltmd6262 

You said that you have integrated the SDK for Android. Can you explain me what did you mean by that? Were you integrating Cocos2d-x SDK in your app and if yes, which version?

As far as I see in the errors (just a guess), it looks like `jobject` which is Android data structure is trying to be accessed and compiled with Xcode. For example, check 2nd exclamation mark in error list saying: `Use of undeclared identifier isEventSet`. I suppose that you have included all header and source files like described in iOS README (https://github.com/adjust/cocos2dx_sdk/blob/master/doc/ios/ios.md) and if you did, you can see that this variable indeed exists: https://github.com/adjust/cocos2dx_sdk/blob/master/Adjust/AdjustEvent2dx.h#L26

It is under `CC_PLATFORM_IOS` preprocessor macro part, but your iOS code tries to compile `jobject` object (https://github.com/adjust/cocos2dx_sdk/blob/master/Adjust/AdjustEvent2dx.h#L24) which is part of `CC_PLATFORM_ANDROID` preprocessor macro part. Are you maybe enforcing `CC_PLATFORM_ANDROID` in your code?

**Comment by dltmd6262** [comment]
Thanks for the reply!

Right now I'm trying to integrate Cocos2d-x SDK version 4.2.0, and it builds fine in Android Studio, but it fails in Xcode with the errors. I kinda figured that the macro was the issue because I also had the issue of jin.h not being found. Can I check on the target platforms and get back to you??

**Comment by uerceg** [comment]
Yep, that would be great. Did you add all source and header files of our SDK to your Xcode project like described in here https://github.com/adjust/cocos2dx_sdk/blob/master/doc/ios/ios.md#2-add-adjust-source-files-to-your-solution ?

**Comment by dltmd6262** [comment]
Yup I added all the files into my Classes folder and tried adding the path to Header Search Paths and still not working :[ let me check the target platform!

**Comment by uerceg** [comment]
Hi @dltmd6262 

Any update on this issue?

**Comment by dltmd6262** [comment]
Oh I totally forgot about this issue.. I'm actually not working on this anymore so I think you should close it!

**Comment by uerceg** [comment]
Feel free to reopen it if needed or create a new one if you have any issues with Cocos2d-x SDK.

Cheers.
