### ISSUE TITLE
Custom Events

### ISSUE THREAD

**Issue by vahid-heidaripour** [adjust/cocos2dx_sdk#35]
I'm using the cocos2dx_sdk for my project. I need to have a few custom events with some parameters. Is it possible to have such a thing?

Thanks.
V.

**Comment by ugi** [comment]
Hi @vahid-heidaripour 

Any update on this one?

**Comment by vahid-heidaripour** [comment]
Hi @ugi 
We managed to not use custom events. The predefined events are pretty enough for our work. 
Thank you.
