### ISSUE TITLE
AdjustSdk 4.23.0 duplicate symbol issue (4.13.0 -> 4.23.0)

### ISSUE THREAD

**Issue by dayfist** [adjust/cocos2dx_sdk#37]
I have issue AdjustSdk 4.23.0 update. How can i fix it?

duplicate symbol '_OBJC_CLASS_$_ADJUrlStrategy' in:
    .../proj.ios_mac/Frameworks/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_METACLASS_$_ADJUrlStrategy' in:
    .../proj.ios_mac/Frameworks/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._gdprUrlChoicesArray' in:
    .../proj.ios_mac/Frameworks/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._subscriptionUrlChoicesArray' in:
    .../proj.ios_mac/Frameworks/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._baseUrlChoicesArray' in:
    .../proj.ios_mac/Frameworks/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._choiceIndex' in:
    .../proj.ios_mac/Frameworks/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._startingChoiceIndex' in:
    .../proj.ios_mac/Frameworks/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._wasLastAttemptSuccess' in:
   .../proj.ios_mac/Frameworks/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._overridenGdprUrl' in:
    .../proj.ios_mac/Frameworks/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._overridenSubscriptionUrl' in:
    .../proj.ios_mac/Frameworks/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._overridenBaseUrl' in:
    .../proj.ios_mac/Frameworks/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._extraPath' in:
    .../proj.ios_mac/Frameworks/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
ld: 12 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ugi** [comment]
Hi @dayfist 

Thanks for reporting, I think we identified where the issue is, will try to follow up with patch update which fixes this during this week. Will keep you posted.

**Comment by dayfist** [comment]
Thank you for answer. I'll wait for the problem to be solved.

**Comment by ugi** [comment]
Hi @dayfist 

Thanks for your patience. We have just released [v4.23.1](https://github.com/adjust/cocos2dx_sdk/releases/tag/v4.23.1) which should hopefully address this issue. Give it a shot and feel free to reopen/comment in case it doesn't fix the issue.

Cheers
